name: Trial job
on: push

jobs:
  example_job:
    name: hogehoge
    runs-on: macos-11.0
    steps:
      - run: echo "example job"
      - run: uname -a
      - run: env
      - run: grep -m1 -o aes /proc/cpuinfo
