name: Trial job
on: push

jobs:
  example_job:
    name: hogehoge
    runs-on: macos-11.0
    steps:
      - run: echo "example job"
      - run: uname -a
      - run: python -c "import platform; print(platform.machine()); print(platform.processor()); print(platform.mac_ver())"
      - run: echo "this is steps after make repository private2"
